#!/usr/bin/perl -w
#
#  (C) 2009 by Argonne National Laboratory.
#      See COPYRIGHT in top-level directory.
#

use Cwd;
use Getopt::Long;
use English;

# files to process
my @csv_files = ();

process_args();

exit 0;

sub process_args
{
    use vars qw( $opt_help );

    Getopt::Long::Configure("no_ignore_case", "bundling");
    GetOptions( "help" );

    if($opt_help)
    {
        print_help();
        exit(0);
    }

    # there should be at least two remaining arguments (file names)
    if($#ARGV < 1)
    {
        print "Error: invalid arguments.\n";
        print_help();
        exit(1);
    }

    @csv_files = @ARGV;

    return;
}

sub print_help
{
    print <<EOF;

Usage: $PROGRAM_NAME file file [file ...]

    --help          Prints this help message

Purpose:

    This script reads multiple csv files generated by fsstats 1.4.5 and
    merges the statistics into a single csv file which is printed to stdout.

EOF
    return;
}
