# Labeler triggered by .github/workflows/labels.yml

pydarshan:
- any: ["darshan-util/pydarshan/**/*"]

performance:
- any: ["darshan-util/pydarshan/benchmarks/**/*"]

CI:
- any: ["**/*.yml"]
- any: ["**/*.yaml"]
- any: [".github/workflows/*.yml"]
- any: [".github/workflows/*.yaml"]
- any: [".github/*.yml"]
- any: [".github/*.yaml"]
