


darshan=/home/pq/ANL/darshan-decaf/testbed/spack/opt/spack/linux-fedora29-x86_64/gcc-8.3.1/darshan-util-fork-onw37xwcivjmpw44onzryhuonj34l7db


all:
	gcc -g -o program stdio_segfault.c -ldarshan-util
