


all:
	@echo "Consult Makefile for available targets."


header:
	./generate-header.sh
	#./apply-patch.sh



clean:
	rm -rf include
	rm -f generated.h
	rm -f generated.h.org

	rm -f generated.h.orig
	rm -f generated.h.rej
