check_PROGRAMS += \
 tests/unit-tests/darshan-accumulator \
 tests/unit-tests/darshan-get-name-records

TESTS += \
 tests/unit-tests/darshan-accumulator \
 tests/unit-tests/run_tests.sh

tests_unit_tests_darshan_accumulator_SOURCES = \
 tests/unit-tests/darshan-accumulator.c \
 tests/unit-tests/munit/munit.c

LDADD = libdarshan-util.la

noinst_HEADERS += \
 tests/unit-tests/munit/munit.h
