name: End-to-end Testing (regression)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
   MPICH_VERSION: 4.3.1

jobs:
  end_to_end_regression:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gfortran bc
      - name: Install MPICH
        run: |
          echo "Install MPICH ${MPICH_VERSION} in ${PWD}/mpich_install"
          mkdir mpich_install
          export MPICH_INSTALL_PATH=$PWD/mpich_install
          wget -q https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz
          tar -xzvf mpich-${MPICH_VERSION}.tar.gz
          cd mpich-${MPICH_VERSION}
          mkdir build
          cd build
          FFLAGS="-w -fallow-argument-mismatch" ../configure --disable-dependency-tracking --prefix=$MPICH_INSTALL_PATH
          make -j8 install
      - name: Install Darshan
        run: |
          git submodule update --init
          export PATH=$PWD/mpich_install/bin:$PATH
          # use automated script to build Darshan
          export DARSHAN_INSTALL_PREFIX=$PWD/darshan_install
          darshan-test/automated/build-darshan.sh
          # try to format log directory to ensure this works
          ./darshan_install/bin/darshan-mk-log-dirs.pl
      - name: Run end-to-end regression tests (ld_preload)
        run: |
          export DARSHAN_INSTALL_PATH=$PWD/darshan_install
          export PATH=$PWD/mpich_install/bin:$PATH
          cd darshan-test/regression
          ./run-all.sh $DARSHAN_INSTALL_PATH /tmp/darshan-ld-preload workstation-ld-preload
      - name: Run end-to-end regression tests (prof conf dynamic)
        run: |
          export DARSHAN_INSTALL_PATH=$PWD/darshan_install
          export PATH=$PWD/mpich_install/bin:$PATH
          cd darshan-test/regression
          ./run-all.sh $DARSHAN_INSTALL_PATH /tmp/darshan-prof-conf-dynamic workstation-profile-conf-dynamic
      - name: Run end-to-end regression tests (prof conf static)
        run: |
          export DARSHAN_INSTALL_PATH=$PWD/darshan_install
          export PATH=$PWD/mpich_install/bin:$PATH
          cd darshan-test/regression
          ./run-all.sh $DARSHAN_INSTALL_PATH /tmp/darshan-prof-conf-static workstation-profile-conf-static
