# Triage PRs based on modified paths
# Rely on .github/pr_path_labeler.yml
# https://github.com/marketplace/actions/labeler
name: "Pull Request Labeler"

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
- pull_request_target

jobs:
  triage-on-file-paths:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/pr_path_labeler.yml"
        sync-labels: true  # remove labels if file not modified anymore
